[package]
name = "pastebin-1"
version = "0.1.0"
edition = "2018"

[dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
tide = "0.16.0"

[[bin]]
name = "pastebin-1"
path = "src/main.rs"
